# Generated by Django 2.0.1 on 2023-10-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0003_auto_20231005_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='date_expired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
    ]
